#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("doge_planner.Resource", IsApplication=true)]

namespace doge_planner
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::doge_planner.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::doge_planner.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int btnBrettMinus1 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int btnBrettMinus10 = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int btnBrettMinus5 = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int btnBrettPlus1 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int btnBrettPlus10 = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int btnBrettPlus5 = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int btnLizMinus1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int btnLizMinus10 = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int btnLizMinus5 = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int btnLizPlus1 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int btnLizPlus10 = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int btnLizPlus5 = 2131034118;
			
			// aapt resource value: 0x7f050017
			public const int btnSusanMinus1 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int btnSusanMinus10 = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int btnSusanMinus5 = 2131034136;
			
			// aapt resource value: 0x7f050014
			public const int btnSusanPlus1 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int btnSusanPlus10 = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int btnSusanPlus5 = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int scoreKeeperButton = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int tesxtView2 = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int textView3 = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int todo = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int txtBrettScore = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int txtLizScore = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int txtSusanScore = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ScoreKeeper = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int scoreKeeper = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
